name: Build LaTeX Document

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  build:
    runs-on: windows-latest  # Use Windows environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MiKTeX
        run: |
          choco install miktex -y  # Install MiKTeX using Chocolatey

      - name: Install latexmk
        run: |
          miktex-console --install latexmk  # Install latexmk using MiKTeX console

      - name: Compile LaTeX with latexmk
        run: |
          latexmk -pdf main.tex  # Compile your main.tex file with latexmk
