name: LaTeX Compilation

on:
  push:
    branches:
      - main

jobs:
  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full
      - name: Compile LaTeX
        run: |
          ./latexmk
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: document
          path: document.pdf
